
manifest = {
    'id': 'sl_list',
    'name': 'SL List',
    'renderer_class': None,
    'manifest_version': 1,
    'requires_departurebox': '0.2.1',
    'optimized_display_sizes': (
        '64x32',
        '128x32',
        '192x32',
        '256x32',
    ),
    'departure_count': 4,
    'supports_tick': True,
    'supported_display_sizes': (
        '64x32',
        '128x32',
        '192x32',
        '256x32',
    ),
    'legacy_listmode': 1,
    'defaults': {
        'maxdest': 4,
        'listcolor': 1,
        'listcolor_time': 1,
        'night_bus_highlight': 0,
        'list_line_display': 1,
        'clocktime': 0,
    },
    'combined_defaults': {
        'maxdest': 5,
        'dest_scroll': 0,
    },
    'ui': {'scroll_selector': False, 'custom_text_requires_custom_mode': False, 'message_interval_custom': False, 'line_display_default': 1},
    'capabilities': {
        'custom_scroll': False,
        'custom_scroll_position': False,
        'scroll_speed': False,
        'clock': True,
        'line_minute_colour': True,
        'clock_extra': True,
        'message_interval': False,
    },
    'web_controls': {'scroll_text': False, 'scroll_selector': False, 'custom_text_requires_custom_mode': False, 'message_interval': False, 'message_interval_custom': False, 'scroll_position': False, 'scroll_speed': False, 'clock': True, 'clock_extra': True, 'line_minute_colour': True, 'line_display_default': 1},
    'show_in_view_menu': True,
}
