manifest = {
    'id': 'sl_modern',
    'name': 'SL Modern',
    'renderer_class': None,
    'manifest_version': 1,
    'requires_departurebox': '0.2.3',
    'optimized_display_sizes': ('128x32', '128x64'),
    'departure_count': 3,
    'supports_tick': True,
    'supported_display_sizes': (
        '128x32',
        '192x32',
        '128x64',
    ),
    'legacy_listmode': 4,
    'defaults': {
        'maxdest': 3,
        'clocktime': 2,
        'list_line_display': 1,
        'listcolor': 0,
        'listcolor_time': 0,
        'night_bus_highlight': 0,
    },
    'combined_defaults': {},
    'capabilities': {
        'line_metadata': True,
        'custom_scroll': True,
        'custom_scroll_position': True,
        'scroll_speed': False,
        'clock': False,
        'line_minute_colour': False,
        'clock_extra': False,
        'message_interval': False,
    },
    'web_controls': {
        'scroll_text': True,
        'scroll_selector': True,
        'custom_text_requires_custom_mode': True,
        'message_interval': False,
        'message_interval_custom': False,
        'scroll_position': True,
        'scroll_position_options': (
            (0, 'Bottom row'),
            (2, 'Middle spacer'),
        ),
        'scroll_speed': False,
        'clock': False,
        'clock_extra': False,
        'line_minute_colour': False,
        'line_display_default': 1,
    },
    'show_in_view_menu': True,
}
