
manifest = {
    'id': 'tfl_dlr',
    'name': 'TfL DLR',
    'renderer_class': None,
    'manifest_version': 1,
    'requires_departurebox': '0.2.1',
    'optimized_display_sizes': ('128x32',),
    'departure_count': 3,
    'supports_tick': True,
    'supported_display_sizes': (
        '128x32',
        '192x32',
    ),
    'legacy_listmode': 2,
    'defaults': {
        'maxdest': 3,
        'listcolor': 0,
        'listcolor_time': 0,
        'night_bus_highlight': 1,
        'list_line_display': 0,
        'clocktime': 2,
        'dlr_scroll_delay': 15,
    },
    'combined_defaults': {},
    'pre_prepare_nightcheck': True,
    'ui': {'scroll_selector': True, 'custom_text_requires_custom_mode': True, 'message_interval_custom': True, 'line_display_default': 0},
    'capabilities': {
        'custom_scroll': True,
        'custom_scroll_position': False,
        'scroll_speed': False,
        'clock': True,
        'line_minute_colour': True,
        'clock_extra': False,
        'message_interval': True,
    },
    'web_controls': {'scroll_text': True, 'scroll_selector': True, 'custom_text_requires_custom_mode': True, 'message_interval': True, 'message_interval_custom': True, 'scroll_position': False, 'scroll_speed': False, 'clock': True, 'clock_extra': False, 'line_minute_colour': True, 'line_display_default': 0},
    'show_in_view_menu': True,
}
